[build]
command = "npm run build"
publish = ".next"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[functions."scheduled-sync"]
schedule = "0 13,14 * * *"

[[plugins]]
package = "@netlify/plugin-nextjs"

[dev]
framework = "next"
